#index:
#    path: /
#    controller: App\Controller\DefaultController::index


index:
  path: /
  controller: App\Controller\MainController::mainAction

forget_password:
  path: /nie-pamietam-hasla
  controller: App\Controller\SecurityController::forgetPassword

reser_password:
  path: /resetuj-haslo/{hash}
  controller: App\Controller\SecurityController::forgetPassword